#index:
#    path: /
#    controller: App\Controller\DefaultController::index

security.login:
  path: /login
  controller: Offerum\Controller\SecurityController:login

security.logout:
  path: /logout

security.register:
  path: /register
  controller: Offerum\Controller\SecurityController:register

offer.index:
  path: /{page}
  controller: Offerum\Controller\OfferController:index
  defaults:
    page: 1
  requirements:
    page: '(?!0)\d+'

offer.create:
  path: /offer/create
  controller: Offerum\Controller\OfferController:create

offer.edit:
  path: /offer/{id}/edit
  controller: Offerum\Controller\OfferController:edit
  requirements:
    id: '\d+'

offer.delete:
  path: /offer/{id}/delete
  controller: Offerum\Controller\OfferController:delete
  requirements:
    id: '\d+'

offer.show:
  path: /offer/{id}
  controller: Offerum\Controller\OfferController:show
  requirements:
    id: '\d+'

user.my_offers:
  path: /my-offers/{page}
  controller: Offerum\Controller\UserController:myOffers
  defaults:
    page: 1
  requirements:
    page: '(?!0)\d+'

user.profile:
  path: /profile/{id}/{page}
  controller: Offerum\Controller\UserController:profile
  defaults:
    page: 1
  requirements:
    id: '\d+'
    page: '(?!0)\d+'